version: "3"

services:

  api:
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    ports:
      - "${FORWARD_APP_PORT:-3000}:3000"
    environment:
      DB_URL: "${DB_URL}"
    networks:
      - itera_net
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "itera_vol:/var/lib/postgresql/data"
    networks:
      - itera_net
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

networks:
  itera_net:
    driver: bridge

volumes:
  itera_vol:
    driver: local
